name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feff71f2f2a13d6912b4e846e537ba93d82944f736dd614577d27eb608736d49"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "resources/datapack"
