name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7eaa5ea5e8870b6c831a46786acf56e5eb3c1b8b7708b3d10d044904d5cadd4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
datapack-folder = "resources/datapack"
