name = "Solstice"
author = "sammyette"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e18f5a57adff7daa8dc084d9dc3472f1e488f57cad0a8a09a394e37a312889fd"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
datapack-folder = "resources/datapack"
